### ISSUE TITLE
Compilation warning: undefined control sequence (pgfutil/pgfmathprintnumber)

### ISSUE THREAD

**Issue by tunesmith** [slithy/rpg_module#12] opened 2024-01-10 05:17 UTC
I recently upgraded to MacTeX 2023, and now whenever I typeset a document that uses rpg-module, I get the following warning:

```
[...]
/usr/local/texlive/2023/texmf-dist/tex/generic/pgf/math/pgfmathfloat.code.tex:1
640: Undefined control sequence.
l.1640 \pgfutil@protected
                         \def\pgfmathprintnumber{%
? 
)) (/Users/curt/Library/texmf/tex/latex/rpg_module/rpg-1e-stats.sty
[...]
```

I've tried reviewing rpg-module.cls and rpg-1e-stats.sty, but haven't found the problem yet... any ideas?

Full error output attached. The test latex document looks like this:

```
\documentclass[letterpaper,serif,1e]{rpg-module}
\begin{document}

Test document

\end{document}
```

[testerr.txt](https://github.com/slithy/rpg_module/files/13883363/testerr.txt)

**Comment by slithy** [comment] 2024-01-10 19:59
Could be Tikz is not fully installed.

What happens if you don't use rpg-module but just include PGF?
```
\documentclass{article}

\usepackage{pgfkeys}
\input{pgfutil-common}
\input{pgfmath.code}

\begin{document}

Test document

\end{document}
```

**Comment by tunesmith** [comment] 2024-01-10 23:26
Yeah, it's something to do with that. I get the same error.

This works:
```
\documentclass{article}

\usepackage{pgfkeys}
\input{pgfutil-common}
%\input{pgfmath.code}

\begin{document}

Test document

\end{document}
```

Not sure what the resolution should be, though?

**Comment by slithy** [comment] 2024-01-11 08:56
I'm guessing a bit, but this could be due to the changes with Shell Escape (see https://tug.org/mactex/TeXLive2023+Changes.pdf).

As I don't have the same installation as you, I can't reproduce the problem to investigate further. Could you post the MWE above on LaTeX StackExchange and see if someone there can help?

**Comment by tunesmith** [comment] 2024-01-13 01:10
Here's the question I asked: https://tex.stackexchange.com/questions/706967/pgfkeys-undefined-control-sequence

For what it's worth, I tried commenting out `\input{pgfmath.code}` in my own instance of rpg-module, and ran 'make' - I can compile my modules without that warning happening now, but I don't really know what pgfkeys and pgfmath.code are supposed to do so I don't have a sense of if I actually broke something else.

**Comment by slithy** [comment] 2024-01-13 14:48
Thanks for following up on that, I have implemented the fix suggested on StackExchange and pushed to main. Closing the issue.

The PGF module provides a set of macros to manage key-value pairs. It is used for the statblocks. I honestly can't remember why `\input` was used instead of `\RequirePackage`.

**Closed as completed by slithy** 2024-01-13 14:48 UTC
